### ISSUE TITLE
Questions/Help if you can

### ISSUE THREAD

**Issue by cowpits** [Luka967/Cigar#81]
@Luka967 thank you for the client, so far I find it the best and smoothest one to play on. 
But players are complaining about lack of mini map and macros for feed and split. Although I use mouse macros, some players don't have settings in their mouse drivers for macros. 
They're also complaining about not having a skin upload option, personally I don't want it because they'll upload inappropriate skins, so that's good on my part. 
Is it possible to add macros and minimap? 
Thanks if you can help with this. 
here's what it looks like on my servers http://gkclan.tk/ 

Sorry one more thing, some fancy characters don't show on leaderboard.

**Comment by Jhair2015** [comment]
do it yourself.

**Comment by cowpits** [comment]
thank you @Jhair2015 
ouch, i'm simply asking for help. sigh.

**Comment by Luka967** [comment]
This is just a base client that meets requirements of the protocol 6. We don't make any further modifications and give server hosters something to work on.

> Sorry one more thing, some fancy characters don't show on leaderboard.

Fixed with commits 064cabf and 8ebdbcd, it was a problem with unicode character writing/reading.

**Comment by cowpits** [comment]
@Luka967 thank you, applied and worked. Much appreciated. 
is there a way to make it default to Retina? It's always defaulting to Medium Quality. 
I've tried this in index.html but it's still defaulting to Medium. 
   <option value="retina" selected>Retina quality</option>

**Comment by Shair17** [comment]
@cowpits Check you have a "checked" next to your retina code

**Comment by cowpits** [comment]
@Jhair2015 in index.html i've changed it to    option value="retina" selected>Retina quality</option>

and in main_out.js i've done this. "retina" was "medium" but that still doesn't stick. 
// Client variables
    var settings = {
        mobile: 'createTouch' in document,
        showMass: false,
        showNames: true,
        showLeaderboard: true,
        showChat: true,
        showGrid: true,
        showTextOutline: true,
        showColor: true,
        showSkins: true,
        darkTheme: false,
        fastRenderMax: .4,
        quality: 'retina',
        qualityRef: qualitySettings['retina'],
        allowGETipSet: false // Whether index.html?ip=abc is accepted (not implemented)
    };

**Comment by cowpits** [comment]
and i realize that it's for mobile. so not sure what else to change

**Comment by Shair17** [comment]
check on your js file

**Comment by Shair17** [comment]
@cowpits That is automatically chosen by the system.
![image](https://cloud.githubusercontent.com/assets/18153674/23761923/866acdaa-04c2-11e7-89c6-921d31831325.png)

**Comment by cowpits** [comment]
that is interesting. I made my window full screen and it picked high quality
[INFO] Loaded, took 279 ms
log.js:24 [DEBUG] Auto-quality high for window size 1920x1080, quality value 12 (real 11.649438202247191), view multiplier 1

i made it a smaller window and it picked Medium
[DEBUG] Auto-quality medium for window size 1481x821, quality value 7 (real 6.830904494382023), view multiplier 0.7601851851851852

**Comment by Shair17** [comment]
lol

**Comment by Luka967** [comment]
The quality auto-selector just measures the canvas' surface area in pixels and divides it by some number which I forgot. The quality value is the output.

**Comment by cowpits** [comment]
can that be changed? if so which file?
